apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-controller
  namespace: argocd
spec:
  destination:
    namespace: arc-systems
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.10.1
    chart: gha-runner-scale-set-controller
    helm:
      parameters:
        - name: image.tag
          value: 0.10.1
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
      - CreateNamespace=true

